# Generated by Django 3.0.2 on 2020-01-16 04:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PuzzlePiece',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField(verbose_name='image url')),
                ('ip_address', models.CharField(max_length=40, verbose_name='submitter ip address')),
                ('submitted_date', models.DateTimeField(auto_now=True, verbose_name='submitted date')),
                ('approved', models.NullBooleanField(verbose_name='is image approved for verification')),
            ],
        ),
        migrations.CreateModel(
            name='Transcription',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_address', models.CharField(max_length=40, verbose_name='submitter ip address')),
                ('submitted_date', models.DateTimeField(auto_now=True, verbose_name='submitted date')),
                ('puzzlePiece', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='collector.PuzzlePiece')),
            ],
        ),
        migrations.CreateModel(
            name='TranscriptionData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bad_image', models.BooleanField(verbose_name='image is bad or hard to read')),
                ('center', models.CharField(max_length=20, verbose_name='center')),
                ('wall1', models.BooleanField(verbose_name='wall 1 (top)')),
                ('wall2', models.BooleanField(verbose_name='wall 2 (top-right)')),
                ('wall3', models.BooleanField(verbose_name='wall 3 (bottom-right)')),
                ('wall4', models.BooleanField(verbose_name='wall 4 (bottom)')),
                ('wall5', models.BooleanField(verbose_name='wall 5 (bottom-left)')),
                ('wall6', models.BooleanField(verbose_name='wall 6 (top-left)')),
                ('link1', models.CharField(max_length=7, verbose_name='link 1 (top)')),
                ('link2', models.CharField(max_length=7, verbose_name='link 2 (top-right)')),
                ('link3', models.CharField(max_length=7, verbose_name='link 3 (bottom-right)')),
                ('link4', models.CharField(max_length=7, verbose_name='link 4 (bottom)')),
                ('link5', models.CharField(max_length=7, verbose_name='link 5 (bottom-left)')),
                ('link6', models.CharField(max_length=7, verbose_name='link 6 (top-left)')),
                ('puzzlePiece', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='collector.PuzzlePiece')),
                ('transcription', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='collector.Transcription')),
            ],
        ),
        migrations.CreateModel(
            name='Confidence',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('confidence', models.PositiveIntegerField(verbose_name='how confident are we in this image, 0 to 100')),
                ('center', models.CharField(max_length=20, verbose_name='center')),
                ('wall1', models.BooleanField(verbose_name='wall 1 (top)')),
                ('wall2', models.BooleanField(verbose_name='wall 2 (top-right)')),
                ('wall3', models.BooleanField(verbose_name='wall 3 (bottom-right)')),
                ('wall4', models.BooleanField(verbose_name='wall 4 (bottom)')),
                ('wall5', models.BooleanField(verbose_name='wall 5 (bottom-left)')),
                ('wall6', models.BooleanField(verbose_name='wall 6 (top-left)')),
                ('link1', models.CharField(max_length=7, verbose_name='link 1 (top)')),
                ('link2', models.CharField(max_length=7, verbose_name='link 2 (top-right)')),
                ('link3', models.CharField(max_length=7, verbose_name='link 3 (bottom-right)')),
                ('link4', models.CharField(max_length=7, verbose_name='link 4 (bottom)')),
                ('link5', models.CharField(max_length=7, verbose_name='link 5 (bottom-left)')),
                ('link6', models.CharField(max_length=7, verbose_name='link 6 (top-left)')),
                ('puzzlePiece', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='collector.PuzzlePiece')),
            ],
        ),
    ]
