# Generated by Django 3.0.2 on 2020-01-16 06:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collector', '0002_puzzlepiece_hash'),
    ]

    operations = [
        migrations.AddField(
            model_name='puzzlepiece',
            name='last_modified',
            field=models.DateTimeField(auto_now=True, verbose_name='last modified date'),
        ),
        migrations.AlterField(
            model_name='puzzlepiece',
            name='submitted_date',
            field=models.DateTimeField(auto_created=True, verbose_name='submitted date'),
        ),
    ]
