# Generated by Django 3.0.2 on 2020-01-16 10:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('collector', '0005_auto_20200116_0231'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transcriptiondata',
            name='puzzlePiece',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transcriptions', to='collector.PuzzlePiece'),
        ),
    ]
