# Generated by Django 3.0.2 on 2020-01-16 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collector', '0008_transcriptiondata_datahash'),
    ]

    operations = [
        migrations.AddField(
            model_name='transcriptiondata',
            name='rawdata',
            field=models.TextField(default='', verbose_name='Raw JSON taken in for later debugging.'),
        ),
    ]
