# Generated by Django 3.0.2 on 2020-01-16 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collector', '0010_auto_20200116_0452'),
    ]

    operations = [
        migrations.AddField(
            model_name='confidencetracking',
            name='last_modified',
            field=models.DateTimeField(auto_now=True, verbose_name='last modified date'),
        ),
        migrations.AddField(
            model_name='confidentsolution',
            name='last_modified',
            field=models.DateTimeField(auto_now=True, verbose_name='last modified date'),
        ),
    ]
