# Generated by Django 3.0.2 on 2020-01-17 04:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('collector', '0012_auto_20200116_0545'),
    ]

    operations = [
        migrations.CreateModel(
            name='BadImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_modified', models.DateTimeField(auto_now=True, verbose_name='last modified date')),
                ('badCount', models.PositiveIntegerField(verbose_name='how often this image was flagged as bad')),
                ('puzzlePiece', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='badimages', to='collector.PuzzlePiece')),
            ],
            options={
                'unique_together': {('id', 'puzzlePiece')},
            },
        ),
    ]
