# Generated by Django 3.0.2 on 2020-01-18 03:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('collector', '0013_badimage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='badimage',
            name='badCount',
            field=models.PositiveIntegerField(verbose_name='how often this image was reported as bad'),
        ),
        migrations.CreateModel(
            name='RotatedImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_modified', models.DateTimeField(auto_now=True, verbose_name='last modified date')),
                ('rotatedCount', models.PositiveIntegerField(verbose_name='how often this image was reported as incorrectly rotated')),
                ('puzzlePiece', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rotatedimages', to='collector.PuzzlePiece')),
            ],
            options={
                'unique_together': {('id', 'puzzlePiece')},
            },
        ),
    ]
