# Generated by Django 3.0.2 on 2020-01-18 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collector', '0014_auto_20200118_0327'),
    ]

    operations = [
        migrations.AddField(
            model_name='puzzlepiece',
            name='transCount',
            field=models.PositiveIntegerField(default=0, verbose_name='Number of transcriptions received for this image'),
        ),
        migrations.AlterField(
            model_name='badimage',
            name='badCount',
            field=models.PositiveIntegerField(default=0, verbose_name='how often this image was reported as bad'),
        ),
        migrations.AlterField(
            model_name='confidencetracking',
            name='confidence',
            field=models.PositiveIntegerField(default=0, verbose_name='how confident are we in this image, 0 to 100'),
        ),
        migrations.AlterField(
            model_name='confidentsolution',
            name='confidence',
            field=models.PositiveIntegerField(default=0, verbose_name='how confident are we in this image, 0 to 100'),
        ),
        migrations.AlterField(
            model_name='puzzlepiece',
            name='ip_address',
            field=models.CharField(default='?.?.?.?', max_length=40, verbose_name='hash of submitter ip address'),
        ),
        migrations.AlterField(
            model_name='rotatedimage',
            name='rotatedCount',
            field=models.PositiveIntegerField(default=0, verbose_name='how often this image was reported as incorrectly rotated'),
        ),
    ]
