# Generated by Django 3.0.2 on 2020-01-18 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collector', '0014_auto_20200118_0327'),
    ]

    operations = [
        migrations.AlterField(
            model_name='puzzlepiece',
            name='ip_address',
            field=models.CharField(default='?.?.?.?', max_length=64, verbose_name='hash of submitter ip address'),
        ),
    ]
