# Generated by Django 3.0.2 on 2020-01-18 16:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('collector', '0015_auto_20200118_1456'),
        ('collector', '0015_auto_20200118_1201'),
    ]

    operations = [
    ]
