# Generated by Django 3.0.2 on 2020-01-18 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collector', '0016_merge_20200118_1626'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transcriptiondata',
            name='ip_address',
            field=models.CharField(default='?.?.?.?', max_length=64, verbose_name='hash of submitter ip address'),
        ),
    ]
