# Generated by Django 3.0.2 on 2020-01-19 21:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collector', '0019_puzzlepiece_priority'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='transcriptiondata',
            index=models.Index(fields=['ip_address'], name='ip_address_idx'),
        ),
    ]
