# Generated by Django 3.0.2 on 2020-01-16 06:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collector', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='puzzlepiece',
            name='hash',
            field=models.CharField(default='empty', max_length=64, unique=True, verbose_name='sha256 hash of the url'),
        ),
    ]
