# Generated by Django 3.0.2 on 2020-01-16 07:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('collector', '0003_auto_20200115_2305'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Confidence',
            new_name='ConfidentSolution',
        ),
        migrations.AddField(
            model_name='transcriptiondata',
            name='orientation',
            field=models.CharField(default='', max_length=10, verbose_name='orientation direction from image'),
        ),
        migrations.AlterField(
            model_name='puzzlepiece',
            name='submitted_date',
            field=models.DateTimeField(auto_now_add=True, verbose_name='submitted date'),
        ),
        migrations.CreateModel(
            name='ConfidenceTracking',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('confidence', models.PositiveIntegerField(verbose_name='how confident are we in this image, 0 to 100')),
                ('puzzlePiece', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='collector.PuzzlePiece')),
            ],
        ),
    ]
