# Generated by Django 3.0.2 on 2020-01-16 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collector', '0004_auto_20200116_0044'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transcriptiondata',
            name='transcription',
        ),
        migrations.AddField(
            model_name='transcriptiondata',
            name='ip_address',
            field=models.CharField(default='?.?.?.?', max_length=40, verbose_name='submitter ip address'),
        ),
        migrations.AddField(
            model_name='transcriptiondata',
            name='submitted_date',
            field=models.DateTimeField(auto_now=True, verbose_name='submitted date'),
        ),
        migrations.AlterField(
            model_name='puzzlepiece',
            name='ip_address',
            field=models.CharField(default='?.?.?.?', max_length=40, verbose_name='submitter ip address'),
        ),
        migrations.DeleteModel(
            name='Transcription',
        ),
    ]
