# Generated by Django 3.0.2 on 2020-01-16 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collector', '0007_auto_20200116_0343'),
    ]

    operations = [
        migrations.AddField(
            model_name='transcriptiondata',
            name='datahash',
            field=models.CharField(default='', max_length=64, verbose_name='sha256 hash for easier comparisons'),
        ),
    ]
