# Generated by Django 3.0.2 on 2020-01-16 11:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('collector', '0009_transcriptiondata_rawdata'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='confidencetracking',
            unique_together={('id', 'puzzlePiece')},
        ),
    ]
