# Generated by Django 3.0.2 on 2020-01-16 12:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('collector', '0011_auto_20200116_0535'),
    ]

    operations = [
        migrations.AlterField(
            model_name='confidencetracking',
            name='puzzlePiece',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='confidences', to='collector.PuzzlePiece'),
        ),
        migrations.AlterField(
            model_name='confidentsolution',
            name='puzzlePiece',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='confidentsolutions', to='collector.PuzzlePiece'),
        ),
    ]
