#!/usr/bin/env bash
setupenv() {
    cp ops/db-dev.env.example ops/db-dev.env
    cp ops/development.env.example ops/development.env
}
build() {
    docker-compose -f ops/docker-compose.dev.yml build
}
inplace() {
    docker-compose -f ops/docker-compose.dev.yml build
    docker-compose -f ops/docker-compose.dev.yml up -d
}
up() {
    docker-compose -f ops/docker-compose.dev.yml up -d
}
down() {
    docker-compose -f ops/docker-compose.dev.yml down
}
restart() {
    docker-compose -f ops/docker-compose.dev.yml down
    docker-compose -f ops/docker-compose.dev.yml up -d
}
logs() {
    docker-compose -f ops/docker-compose.dev.yml logs
}
logsf() {
    docker-compose -f ops/docker-compose.dev.yml logs -f
}
exec() {
    docker-compose -f ops/docker-compose.dev.yml exec $@
}
cmd() {
    docker-compose -f ops/docker-compose.dev.yml $@
}
command=${1}
shift
${command} $@